-- MySQL Script generated by MySQL Workbench
-- lun 15 mar 2021 19:15:19
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema objectboard_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema objectboard_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `objectboard_db` DEFAULT CHARACTER SET utf8 ;
USE `objectboard_db` ;

-- -----------------------------------------------------
-- Table `objectboard_db`.`country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `objectboard_db`.`country` ;

CREATE TABLE IF NOT EXISTS `objectboard_db`.`country` (
  `co_country_code` BIGINT(3) NOT NULL AUTO_INCREMENT,
  `co_name` VARCHAR(40) NULL,
  PRIMARY KEY (`co_country_code`))
ENGINE = InnoDB
COMMENT = 'Country list';


-- -----------------------------------------------------
-- Table `objectboard_db`.`states`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `objectboard_db`.`states` ;

CREATE TABLE IF NOT EXISTS `objectboard_db`.`states` (
  `st_state_code` BIGINT(2) NOT NULL AUTO_INCREMENT,
  `country_co_country_code` BIGINT(3) NOT NULL,
  `st_name` VARCHAR(45) NULL,
  PRIMARY KEY (`st_state_code`, `country_co_country_code`),
  CONSTRAINT `fk_states_country1`
    FOREIGN KEY (`country_co_country_code`)
    REFERENCES `objectboard_db`.`country` (`co_country_code`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'State List';

CREATE INDEX `fk_states_country1_idx` ON `objectboard_db`.`states` (`country_co_country_code` ASC);


-- -----------------------------------------------------
-- Table `objectboard_db`.`city`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `objectboard_db`.`city` ;

CREATE TABLE IF NOT EXISTS `objectboard_db`.`city` (
  `ci_city_code` BIGINT(3) NOT NULL AUTO_INCREMENT,
  `states_st_state_code` BIGINT(2) NOT NULL,
  `states_country_co_country_code` BIGINT(3) NOT NULL,
  `ci_name` VARCHAR(45) NULL,
  PRIMARY KEY (`ci_city_code`, `states_st_state_code`, `states_country_co_country_code`),
  CONSTRAINT `fk_city_states1`
    FOREIGN KEY (`states_st_state_code` , `states_country_co_country_code`)
    REFERENCES `objectboard_db`.`states` (`st_state_code` , `country_co_country_code`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'City List';

CREATE INDEX `fk_city_states1_idx` ON `objectboard_db`.`city` (`states_st_state_code` ASC, `states_country_co_country_code` ASC);


-- -----------------------------------------------------
-- Table `objectboard_db`.`bussinessType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `objectboard_db`.`bussinessType` ;

CREATE TABLE IF NOT EXISTS `objectboard_db`.`bussinessType` (
  `bt_code_type` BIGINT(2) NOT NULL AUTO_INCREMENT,
  `bt_description` VARCHAR(45) NOT NULL,
  `bt_note` VARCHAR(85) NULL,
  PRIMARY KEY (`bt_code_type`))
ENGINE = InnoDB
COMMENT = 'type of business unit';


-- -----------------------------------------------------
-- Table `objectboard_db`.`bussinessUnit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `objectboard_db`.`bussinessUnit` ;

CREATE TABLE IF NOT EXISTS `objectboard_db`.`bussinessUnit` (
  `bu_bis_code` BIGINT(4) NOT NULL AUTO_INCREMENT COMMENT 'Clavede la tabla - numero de la empresa',
  `bu_federal_number` VARCHAR(10) NULL,
  `bu_provincial_number` VARCHAR(16) NULL,
  `bu_email` VARCHAR(60) NULL,
  `bu_status` VARCHAR(1) NOT NULL DEFAULT 'T' COMMENT '1 ACTIVE 0 INACTIVE',
  `bu_super_code` VARCHAR(12) NULL COMMENT 'COMPANY CODE TO REGISTER ADMINISTRATORS',
  `bu_phone` VARCHAR(13) NULL,
  `bu_zipcode` VARCHAR(6) NULL,
  `bu_name` VARCHAR(35) NULL,
  `bu_address` VARCHAR(45) NULL,
  `bu_webpage` VARCHAR(50) NULL,
  `bu_admin_code` VARCHAR(12) NULL,
  `bu_user1_code` VARCHAR(12) NULL,
  `bu_user2_code` VARCHAR(12) NULL,
  `city_ci_city_code` BIGINT(3) NOT NULL,
  `city_states_st_state_code` BIGINT(2) NOT NULL,
  `city_states_country_co_country_code` BIGINT(3) NOT NULL,
  `bussinessType_bt_code_type` BIGINT(2) NOT NULL,
  `bu_logo_name` VARCHAR(45) NOT NULL DEFAULT 'favicon2.png',
  `bu_logo_image` BLOB NULL,
  PRIMARY KEY (`bu_bis_code`),
  CONSTRAINT `fk_bussinessUnit_city1`
    FOREIGN KEY (`city_ci_city_code` , `city_states_st_state_code` , `city_states_country_co_country_code`)
    REFERENCES `objectboard_db`.`city` (`ci_city_code` , `states_st_state_code` , `states_country_co_country_code`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bussinessUnit_bussinessType1`
    FOREIGN KEY (`bussinessType_bt_code_type`)
    REFERENCES `objectboard_db`.`bussinessType` (`bt_code_type`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_bussinessUnit_city1_idx` ON `objectboard_db`.`bussinessUnit` (`city_ci_city_code` ASC, `city_states_st_state_code` ASC, `city_states_country_co_country_code` ASC);

CREATE INDEX `fk_bussinessUnit_bussinessType1_idx` ON `objectboard_db`.`bussinessUnit` (`bussinessType_bt_code_type` ASC);


-- -----------------------------------------------------
-- Table `objectboard_db`.`project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `objectboard_db`.`project` ;

CREATE TABLE IF NOT EXISTS `objectboard_db`.`project` (
  `pr_id_project` BIGINT(2) NOT NULL AUTO_INCREMENT,
  `pr_name` VARCHAR(45) NOT NULL,
  `pr_note` VARCHAR(145) NULL,
  PRIMARY KEY (`pr_id_project`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `objectboard_db`.`discharge`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `objectboard_db`.`discharge` ;

CREATE TABLE IF NOT EXISTS `objectboard_db`.`discharge` (
  `di_license_num` BIGINT(8) NOT NULL AUTO_INCREMENT,
  `di_start_date` VARCHAR(19) NOT NULL,
  `di_end_date` VARCHAR(19) NOT NULL,
  `di_number_user` INT(3) NULL,
  `di_permanent` VARCHAR(1) NULL DEFAULT 'F',
  `di_sales_code` INT(2) NULL DEFAULT 0,
  `di_license_code` VARCHAR(16) NOT NULL,
  `bussinessUnit_bu_bis_code` BIGINT(4) NOT NULL,
  `project_pr_id_project` BIGINT(2) NOT NULL,
  PRIMARY KEY (`di_license_num`),
  CONSTRAINT `fk_discharge_bussinessUnit1`
    FOREIGN KEY (`bussinessUnit_bu_bis_code`)
    REFERENCES `objectboard_db`.`bussinessUnit` (`bu_bis_code`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_discharge_project1`
    FOREIGN KEY (`project_pr_id_project`)
    REFERENCES `objectboard_db`.`project` (`pr_id_project`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_discharge_bussinessUnit1_idx` ON `objectboard_db`.`discharge` (`bussinessUnit_bu_bis_code` ASC);

CREATE INDEX `fk_discharge_project1_idx` ON `objectboard_db`.`discharge` (`project_pr_id_project` ASC);


-- -----------------------------------------------------
-- Table `objectboard_db`.`masterUser`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `objectboard_db`.`masterUser` ;

CREATE TABLE IF NOT EXISTS `objectboard_db`.`masterUser` (
  `mu_email` VARCHAR(40) NOT NULL,
  `bussinessUnit_bu_bis_code` BIGINT(4) NOT NULL,
  `mu_password` VARCHAR(20) NOT NULL,
  `mu_password_old` VARCHAR(20) NULL,
  `mu_name` VARCHAR(45) NULL,
  `mu_section_time` INT(11) NULL DEFAULT 1200 COMMENT 'TIEMPO QUE PERMANECE ABIERTA LA SECCION EN DESUSO',
  `mu_question` VARCHAR(60) NULL,
  `mu_start_date` VARCHAR(19) NOT NULL COMMENT 'start date ',
  `mu_answer` VARCHAR(35) NULL,
  `mu_status` VARCHAR(1) NOT NULL DEFAULT 'F' COMMENT '0 INACTIVE 1 ACTIVE',
  `mu_date` VARCHAR(19) NOT NULL COMMENT 'REGISTER DATE',
  `mu_effective_days` INT(4) NOT NULL DEFAULT 90 COMMENT 'renovation password days',
  `mu_confirm_code` VARCHAR(45) NULL,
  `mu_email_confirm` VARCHAR(1) NULL DEFAULT 'F' COMMENT '0 UNCONFIRM 1 CONFIRM',
  `mu_date_reset_pwd` VARCHAR(19) NULL,
  `mu_gender` VARCHAR(1) NULL DEFAULT 'M',
  `mu_photo` BLOB NULL,
  `mu_data_user` VARCHAR(12) NULL COMMENT 'long para accesar la base de datos',
  `mu_data_password` VARCHAR(16) NULL,
  `mu_expires` VARCHAR(1) NULL DEFAULT 'F',
  `mu_date_expires` VARCHAR(19) NULL DEFAULT 90,
  `city_ci_city_code` BIGINT(3) NOT NULL,
  `city_states_st_state_code` BIGINT(2) NOT NULL COMMENT 'EL ACCESO AL SISTEMA CADUCA O NO',
  `city_states_country_co_country_code` BIGINT(3) NOT NULL,
  `mu_photo_name` VARCHAR(45) NULL,
  PRIMARY KEY (`mu_email`, `bussinessUnit_bu_bis_code`),
  CONSTRAINT `fk_masterUser_bussinessUnit1`
    FOREIGN KEY (`bussinessUnit_bu_bis_code`)
    REFERENCES `objectboard_db`.`bussinessUnit` (`bu_bis_code`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_masterUser_city1`
    FOREIGN KEY (`city_ci_city_code` , `city_states_st_state_code` , `city_states_country_co_country_code`)
    REFERENCES `objectboard_db`.`city` (`ci_city_code` , `states_st_state_code` , `states_country_co_country_code`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_masterUser_bussinessUnit1_idx` ON `objectboard_db`.`masterUser` (`bussinessUnit_bu_bis_code` ASC);

CREATE INDEX `fk_masterUser_city1_idx` ON `objectboard_db`.`masterUser` (`city_ci_city_code` ASC, `city_states_st_state_code` ASC, `city_states_country_co_country_code` ASC);


-- -----------------------------------------------------
-- Table `objectboard_db`.`userRole`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `objectboard_db`.`userRole` ;

CREATE TABLE IF NOT EXISTS `objectboard_db`.`userRole` (
  `masterUser_mu_email` VARCHAR(40) NOT NULL,
  `masterUser_bussinessUnit_bu_bis_code` BIGINT(4) NOT NULL,
  `project_pr_id_project` BIGINT(2) NOT NULL,
  `um_role` INT(2) NOT NULL DEFAULT 0 COMMENT 'INTRANET USERS',
  `um_status` VARCHAR(1) NULL DEFAULT 'T' COMMENT 'active or not',
  PRIMARY KEY (`masterUser_mu_email`, `masterUser_bussinessUnit_bu_bis_code`, `project_pr_id_project`),
  CONSTRAINT `fk_userRole_masterUser1`
    FOREIGN KEY (`masterUser_mu_email` , `masterUser_bussinessUnit_bu_bis_code`)
    REFERENCES `objectboard_db`.`masterUser` (`mu_email` , `bussinessUnit_bu_bis_code`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_userRole_project1`
    FOREIGN KEY (`project_pr_id_project`)
    REFERENCES `objectboard_db`.`project` (`pr_id_project`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'modules to which each user has access by business unit';

CREATE INDEX `fk_userRole_project1_idx` ON `objectboard_db`.`userRole` (`project_pr_id_project` ASC);


-- -----------------------------------------------------
-- Table `objectboard_db`.`Log_country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `objectboard_db`.`Log_country` ;

CREATE TABLE IF NOT EXISTS `objectboard_db`.`Log_country` (
  `co_country_code` BIGINT(3) NULL,
  `co_name` VARCHAR(40) NULL,
  `co_name_old` VARCHAR(40) NULL,
  `action_type` VARCHAR(8) NULL DEFAULT NULL,
  `action_who` VARCHAR(12) NULL DEFAULT NULL,
  `action_time` VARCHAR(20) NULL DEFAULT NULL)
ENGINE = InnoDB
COMMENT = 'log Countries';


-- -----------------------------------------------------
-- Table `objectboard_db`.`Log_state`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `objectboard_db`.`Log_state` ;

CREATE TABLE IF NOT EXISTS `objectboard_db`.`Log_state` (
  `st_state_code` BIGINT(2) NULL,
  `country_co_country_code` BIGINT(3) NULL,
  `st_name` VARCHAR(45) NULL,
  `st_name_ant` VARCHAR(45) NULL,
  `action_type` VARCHAR(8) NULL DEFAULT NULL,
  `action_who` VARCHAR(12) NULL DEFAULT NULL,
  `action_time` VARCHAR(20) NULL DEFAULT NULL)
ENGINE = InnoDB
COMMENT = 'Log states';


-- -----------------------------------------------------
-- Table `objectboard_db`.`Log_city`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `objectboard_db`.`Log_city` ;

CREATE TABLE IF NOT EXISTS `objectboard_db`.`Log_city` (
  `ci_city_code` BIGINT(3) NULL,
  `states_st_state_code` BIGINT(2) NULL,
  `states_country_co_country_code` BIGINT(3) NULL,
  `ci_name` VARCHAR(45) NULL,
  `ci_name_ant` VARCHAR(45) NULL,
  `action_type` VARCHAR(8) NULL DEFAULT NULL,
  `action_who` VARCHAR(12) NULL DEFAULT NULL,
  `action_time` VARCHAR(20) NULL DEFAULT NULL)
ENGINE = InnoDB
COMMENT = 'Log cities';


-- -----------------------------------------------------
-- Table `objectboard_db`.`Log_masterUser`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `objectboard_db`.`Log_masterUser` ;

CREATE TABLE IF NOT EXISTS `objectboard_db`.`Log_masterUser` (
  `mu_email` VARCHAR(40) NULL,
  `bussinessUnit_bu_bis_code` BIGINT(4) NULL,
  `mu_password` VARCHAR(20) NULL,
  `mu_password_ant` VARCHAR(20) NULL,
  `mu_password_old` VARCHAR(20) NULL,
  `mu_password_old_ant` VARCHAR(20) NULL,
  `mu_name` VARCHAR(45) NULL,
  `mu_name_ant` VARCHAR(45) NULL,
  `mu_section_time` INT(11) NULL DEFAULT 1200 COMMENT 'TIEMPO QUE PERMANECE ABIERTA LA SECCION EN DESUSO',
  `mu_section_time_ant` INT(11) NULL,
  `mu_question` VARCHAR(60) NULL,
  `mu_question_ant` VARCHAR(60) NULL,
  `mu_start_date` VARCHAR(19) NULL COMMENT 'start date ',
  `mu_start_date_ant` VARCHAR(19) NULL COMMENT 'start date ',
  `mu_answer` VARCHAR(35) NULL,
  `mu_answer_ant` VARCHAR(35) NULL,
  `mu_status` VARCHAR(1) NULL DEFAULT 'F' COMMENT '0 INACTIVE 1 ACTIVE',
  `mu_status_ant` VARCHAR(1) NULL DEFAULT 'F' COMMENT '0 INACTIVE 1 ACTIVE',
  `mu_date` VARCHAR(19) NULL COMMENT 'REGISTER DATE',
  `mu_date_ant` VARCHAR(19) NULL COMMENT 'REGISTER DATE',
  `mu_effective_days` INT(4) NULL DEFAULT 90 COMMENT 'renovation password days',
  `mu_effective_days_ant` INT(4) NULL DEFAULT 90 COMMENT 'renovation password days',
  `mu_confirm_code` VARCHAR(45) NULL,
  `mu_confirm_code_ant` VARCHAR(45) NULL,
  `mu_email_confirm` VARCHAR(1) NULL DEFAULT 'F' COMMENT '0 UNCONFIRM 1 CONFIRM',
  `mu_email_confirm_ant` VARCHAR(1) NULL DEFAULT 'F' COMMENT '0 UNCONFIRM 1 CONFIRM',
  `mu_date_reset_pwd` VARCHAR(19) NULL,
  `mu_date_reset_pwd_ant` VARCHAR(19) NULL,
  `mu_gender` VARCHAR(1) NULL DEFAULT 'M',
  `mu_gender_ant` VARCHAR(1) NULL DEFAULT 'M',
  `mu_photo` BLOB NULL,
  `mu_photo_ant` BLOB NULL,
  `mu_data_user` VARCHAR(12) NULL COMMENT 'long para accesar la base de datos',
  `mu_data_user_ant` VARCHAR(12) NULL COMMENT 'long para accesar la base de datos',
  `mu_data_password` VARCHAR(16) NULL,
  `mu_data_password_ant` VARCHAR(16) NULL,
  `mu_expires` VARCHAR(1) NULL DEFAULT 'F',
  `mu_expires_ant` VARCHAR(1) NULL DEFAULT 'F',
  `mu_date_expires` VARCHAR(19) NULL DEFAULT 90,
  `mu_date_expires_ant` VARCHAR(19) NULL DEFAULT 90,
  `city_ci_city_code` BIGINT(3) NULL,
  `city_ci_city_code_ant` BIGINT(3) NULL,
  `city_states_st_state_code` BIGINT(2) NULL COMMENT 'EL ACCESO AL SISTEMA CADUCA O NO',
  `city_states_st_state_code_ant` BIGINT(2) NULL COMMENT 'EL ACCESO AL SISTEMA CADUCA O NO',
  `city_states_country_co_country_code` BIGINT(3) NULL,
  `city_states_country_co_country_code_ant` BIGINT(3) NULL,
  `action_type` VARCHAR(8) NULL DEFAULT NULL,
  `action_who` VARCHAR(12) NULL DEFAULT NULL,
  `action_time` VARCHAR(20) NULL DEFAULT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `objectboard_db`.`Log_bussinessType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `objectboard_db`.`Log_bussinessType` ;

CREATE TABLE IF NOT EXISTS `objectboard_db`.`Log_bussinessType` (
  `bt_code_type` BIGINT(2) NULL,
  `bt_description` VARCHAR(45) NULL,
  `bt_description_old` VARCHAR(45) NULL,
  `bt_note` VARCHAR(85) NULL,
  `bt_note_old` VARCHAR(85) NULL,
  `action_type` VARCHAR(8) NULL DEFAULT NULL,
  `action_who` VARCHAR(12) NULL DEFAULT NULL,
  `action_time` VARCHAR(20) NULL DEFAULT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `objectboard_db`.`Log_project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `objectboard_db`.`Log_project` ;

CREATE TABLE IF NOT EXISTS `objectboard_db`.`Log_project` (
  `pr_id_project` BIGINT(2) NULL,
  `pr_name` VARCHAR(45) NULL,
  `pr_name_old` VARCHAR(45) NULL,
  `pr_note` VARCHAR(145) NULL,
  `pr_note_old` VARCHAR(145) NULL,
  `action_type` VARCHAR(8) NULL DEFAULT NULL,
  `action_who` VARCHAR(12) NULL DEFAULT NULL,
  `action_time` VARCHAR(20) NULL DEFAULT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `objectboard_db`.`Log_bussinessUnit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `objectboard_db`.`Log_bussinessUnit` ;

CREATE TABLE IF NOT EXISTS `objectboard_db`.`Log_bussinessUnit` (
  `bu_bis_code` BIGINT(4) NULL COMMENT 'Clavede la tabla - numero de la empresa',
  `bu_federal_number` VARCHAR(10) NULL,
  `bu_provincial_number` VARCHAR(16) NULL,
  `bu_email` VARCHAR(60) NULL,
  `bu_status` VARCHAR(1) NULL COMMENT '1 ACTIVE 0 INACTIVE',
  `bu_super_code` VARCHAR(12) NULL COMMENT 'COMPANY CODE TO REGISTER ADMINISTRATORS',
  `bu_phone` VARCHAR(13) NULL,
  `bu_zipcode` VARCHAR(6) NULL,
  `bu_name` VARCHAR(35) NULL,
  `bu_address` VARCHAR(45) NULL,
  `bu_webpage` VARCHAR(50) NULL,
  `bu_admin_code` VARCHAR(12) NULL,
  `bu_user1_code` VARCHAR(12) NULL,
  `bu_user2_code` VARCHAR(12) NULL,
  `city_ci_city_code` BIGINT(3) NULL,
  `city_states_st_state_code` BIGINT(2) NULL,
  `city_states_country_co_country_code` BIGINT(3) NULL,
  `bussinessType_bt_code_type` BIGINT(2) NULL,
  `bu_federal_number_old` VARCHAR(10) NULL,
  `bu_provincial_number_old` VARCHAR(16) NULL,
  `bu_email_old` VARCHAR(60) NULL,
  `bu_status_old` VARCHAR(1) NULL COMMENT '1 ACTIVE 0 INACTIVE',
  `bu_super_code_old` VARCHAR(12) NULL COMMENT 'COMPANY CODE TO REGISTER ADMINISTRATORS',
  `bu_phone_old` VARCHAR(13) NULL,
  `bu_zipcode_old` VARCHAR(6) NULL,
  `bu_name_old` VARCHAR(35) NULL,
  `bu_address_old` VARCHAR(45) NULL,
  `bu_webpage_old` VARCHAR(50) NULL,
  `bu_admin_code_old` VARCHAR(12) NULL,
  `bu_user1_code_old` VARCHAR(12) NULL,
  `bu_user2_code_old` VARCHAR(12) NULL,
  `city_ci_city_code_old` BIGINT(3) NULL,
  `city_states_st_state_code_old` BIGINT(2) NULL,
  `city_states_country_co_country_code_old` BIGINT(3) NULL,
  `bussinessType_bt_code_type_old` BIGINT(2) NULL,
  `action_type` VARCHAR(8) NULL DEFAULT NULL,
  `action_who` VARCHAR(12) NULL DEFAULT NULL,
  `action_time` VARCHAR(20) NULL DEFAULT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `objectboard_db`.`Log_discharge`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `objectboard_db`.`Log_discharge` ;

CREATE TABLE IF NOT EXISTS `objectboard_db`.`Log_discharge` (
  `di_license_num` BIGINT(8) NULL,
  `di_start_date` VARCHAR(19) NULL,
  `di_end_date` VARCHAR(19) NULL,
  `di_number_user` INT(3) NULL,
  `di_permanent` VARCHAR(1) NULL,
  `di_sales_code` INT(2) NULL,
  `di_license_code` VARCHAR(16) NULL,
  `bussinessUnit_bu_bis_code` BIGINT(4) NULL,
  `project_pr_id_project` BIGINT(2) NULL,
  `di_start_date_old` VARCHAR(19) NULL,
  `di_end_date_old` VARCHAR(19) NULL,
  `di_number_user_old` INT(3) NULL,
  `di_permanent_old` VARCHAR(1) NULL,
  `di_sales_code_old` INT(2) NULL DEFAULT 0,
  `di_license_code_old` VARCHAR(16) NULL,
  `bussinessUnit_bu_bis_code_old` BIGINT(4) NULL,
  `project_pr_id_project_old` BIGINT(2) NULL,
  `action_type` VARCHAR(8) NULL DEFAULT NULL,
  `action_who` VARCHAR(12) NULL DEFAULT NULL,
  `action_time` VARCHAR(20) NULL DEFAULT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `objectboard_db`.`Log_userRole`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `objectboard_db`.`Log_userRole` ;

CREATE TABLE IF NOT EXISTS `objectboard_db`.`Log_userRole` (
  `masterUser_mu_email` VARCHAR(40) NULL,
  `masterUser_bussinessUnit_bu_bis_code` BIGINT(4) NULL,
  `project_pr_id_project` BIGINT(2) NULL,
  `um_role` INT(2) NULL COMMENT 'INTRANET USERS',
  `um_status` VARCHAR(1) NULL COMMENT 'active or not',
  `um_role_old` INT(2) NULL COMMENT 'INTRANET USERS',
  `um_status_old` VARCHAR(1) NULL COMMENT 'active or not',
  `action_type` VARCHAR(8) NULL DEFAULT NULL,
  `action_who` VARCHAR(12) NULL DEFAULT NULL,
  `action_time` VARCHAR(20) NULL DEFAULT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `objectboard_db`.`typified`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `objectboard_db`.`typified` ;

CREATE TABLE IF NOT EXISTS `objectboard_db`.`typified` (
  `bussinessUnit_bu_bis_code` BIGINT(4) NOT NULL,
  `ctypified_code1` VARCHAR(30) NOT NULL,
  `ctypified_code2` VARCHAR(30) NOT NULL,
  `ctypified_code3` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`bussinessUnit_bu_bis_code`, `ctypified_code1`, `ctypified_code2`, `ctypified_code3`),
  CONSTRAINT `fk_typified1_bussinessUnit1`
    FOREIGN KEY (`bussinessUnit_bu_bis_code`)
    REFERENCES `objectboard_db`.`bussinessUnit` (`bu_bis_code`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_typified1_bussinessUnit1_idx` ON `objectboard_db`.`typified` (`bussinessUnit_bu_bis_code` ASC);


-- -----------------------------------------------------
-- Table `objectboard_db`.`organization`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `objectboard_db`.`organization` ;

CREATE TABLE IF NOT EXISTS `objectboard_db`.`organization` (
  `bussinessUnit_bu_bis_code` BIGINT(4) NOT NULL,
  `level1` VARCHAR(45) NOT NULL,
  `level2` VARCHAR(45) NOT NULL,
  `level3` VARCHAR(45) NOT NULL,
  `level4` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`bussinessUnit_bu_bis_code`, `level1`, `level2`, `level3`, `level4`),
  CONSTRAINT `fk_organization_bussinessUnit1`
    FOREIGN KEY (`bussinessUnit_bu_bis_code`)
    REFERENCES `objectboard_db`.`bussinessUnit` (`bu_bis_code`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_organization_bussinessUnit1_idx` ON `objectboard_db`.`organization` (`bussinessUnit_bu_bis_code` ASC);


-- -----------------------------------------------------
-- Table `objectboard_db`.`headersSurvey`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `objectboard_db`.`headersSurvey` ;

CREATE TABLE IF NOT EXISTS `objectboard_db`.`headersSurvey` (
  `survey_code` BIGINT(8) NOT NULL AUTO_INCREMENT,
  `bussinessUnit_bu_bis_code` BIGINT(4) NOT NULL,
  `hs_name` VARCHAR(45) NOT NULL DEFAULT 'NA',
  `hs_references` VARCHAR(8) NULL,
  `total_questions` INT(3) NULL DEFAULT 0,
  `surveyStatus` VARCHAR(1) NULL,
  `execution_status` VARCHAR(1) NOT NULL DEFAULT 'F',
  `version` INT(3) NOT NULL DEFAULT 1,
  `date_creation` VARCHAR(19) NOT NULL,
  `typified_bussinessUnit_bu_bis_code` BIGINT(4) NOT NULL,
  `typified_ctypified_code1` VARCHAR(30) NOT NULL,
  `typified_ctypified_code2` VARCHAR(30) NOT NULL,
  `typified_ctypified_code3` VARCHAR(30) NOT NULL,
  `organization_bussinessUnit_bu_bis_code` BIGINT(4) NOT NULL,
  `organization_level1` VARCHAR(45) NOT NULL,
  `organization_level2` VARCHAR(45) NOT NULL,
  `organization_level3` VARCHAR(45) NOT NULL,
  `organization_level4` VARCHAR(45) NOT NULL,
  `date_last_modification` VARCHAR(19) NULL,
  `audited` VARCHAR(1) NOT NULL DEFAULT 'F',
  `total_points` DOUBLE NOT NULL DEFAULT 0,
  `survey_image_name` VARCHAR(45) NULL,
  `survey_image_file` LONGBLOB NULL,
  PRIMARY KEY (`survey_code`, `bussinessUnit_bu_bis_code`),
  CONSTRAINT `fk_headersQuestions_bussinessUnit1`
    FOREIGN KEY (`bussinessUnit_bu_bis_code`)
    REFERENCES `objectboard_db`.`bussinessUnit` (`bu_bis_code`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_headersSurvey_typified1`
    FOREIGN KEY (`typified_bussinessUnit_bu_bis_code` , `typified_ctypified_code1` , `typified_ctypified_code2` , `typified_ctypified_code3`)
    REFERENCES `objectboard_db`.`typified` (`bussinessUnit_bu_bis_code` , `ctypified_code1` , `ctypified_code2` , `ctypified_code3`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_headersSurvey_organization1`
    FOREIGN KEY (`organization_bussinessUnit_bu_bis_code` , `organization_level1` , `organization_level2` , `organization_level3` , `organization_level4`)
    REFERENCES `objectboard_db`.`organization` (`bussinessUnit_bu_bis_code` , `level1` , `level2` , `level3` , `level4`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_headersQuestions_bussinessUnit1_idx` ON `objectboard_db`.`headersSurvey` (`bussinessUnit_bu_bis_code` ASC);

CREATE INDEX `fk_headersSurvey_typified1_idx` ON `objectboard_db`.`headersSurvey` (`typified_bussinessUnit_bu_bis_code` ASC, `typified_ctypified_code1` ASC, `typified_ctypified_code2` ASC, `typified_ctypified_code3` ASC);

CREATE INDEX `fk_headersSurvey_organization1_idx` ON `objectboard_db`.`headersSurvey` (`organization_bussinessUnit_bu_bis_code` ASC, `organization_level1` ASC, `organization_level2` ASC, `organization_level3` ASC, `organization_level4` ASC);


-- -----------------------------------------------------
-- Table `objectboard_db`.`bodySurveyQuestions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `objectboard_db`.`bodySurveyQuestions` ;

CREATE TABLE IF NOT EXISTS `objectboard_db`.`bodySurveyQuestions` (
  `question_code` BIGINT(4) NOT NULL AUTO_INCREMENT,
  `headersSurvey_survey_code` BIGINT(8) NOT NULL,
  `headersSurvey_bussinessUnit_bu_bis_code` BIGINT(4) NOT NULL,
  `type_request` INT(2) NOT NULL DEFAULT 0,
  `main_request` VARCHAR(160) NULL,
  `Annex_type` VARCHAR(1) NULL,
  `body_annex_doc` VARCHAR(45) NULL,
  `body_annex_photo` VARCHAR(45) NULL,
  `comment` VARCHAR(1) NULL DEFAULT 'F',
  `answer_number` INT(2) NOT NULL DEFAULT 0,
  `solution_number` INT(2) NOT NULL DEFAULT 0,
  `auditable_solution` VARCHAR(1) NOT NULL DEFAULT 'F',
  `auditable_answer_solution` VARCHAR(1) NOT NULL DEFAULT 'F',
  `question_points` DOUBLE NOT NULL DEFAULT 1,
  `status_rank` VARCHAR(1) NOT NULL DEFAULT 'F',
  `question_image_name` VARCHAR(45) NULL,
  `question_image_file` LONGBLOB NULL,
  PRIMARY KEY (`question_code`, `headersSurvey_survey_code`, `headersSurvey_bussinessUnit_bu_bis_code`),
  CONSTRAINT `fk_bodySurvey_headersSurvey1`
    FOREIGN KEY (`headersSurvey_survey_code` , `headersSurvey_bussinessUnit_bu_bis_code`)
    REFERENCES `objectboard_db`.`headersSurvey` (`survey_code` , `bussinessUnit_bu_bis_code`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_bodySurvey_headersSurvey1_idx` ON `objectboard_db`.`bodySurveyQuestions` (`headersSurvey_survey_code` ASC, `headersSurvey_bussinessUnit_bu_bis_code` ASC);


-- -----------------------------------------------------
-- Table `objectboard_db`.`bodySurveyAnswers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `objectboard_db`.`bodySurveyAnswers` ;

CREATE TABLE IF NOT EXISTS `objectboard_db`.`bodySurveyAnswers` (
  `answer_code` BIGINT(4) NOT NULL AUTO_INCREMENT,
  `bodySurveyQuestions_question_code` BIGINT(4) NOT NULL,
  `bodySurveyQuestions_headersSurvey_survey_code` BIGINT(8) NOT NULL,
  `bodySurveyQuestions_headersSurvey_bussinessUnit_bu_bis_code` BIGINT(4) NOT NULL,
  `answer` VARCHAR(65) NOT NULL,
  `answer_solution` VARCHAR(1) NOT NULL DEFAULT 'F',
  `auditable_solution` VARCHAR(1) NOT NULL DEFAULT 'F',
  `answer_only_text` VARCHAR(45) NULL,
  `answer_only_number` DOUBLE NOT NULL DEFAULT 0,
  `answer_only_date` VARCHAR(10) NULL,
  `answer_only_time` VARCHAR(8) NULL,
  `status_rank` VARCHAR(1) NOT NULL DEFAULT 'F',
  `rank_min` DOUBLE NOT NULL DEFAULT 0,
  `rank_max` DOUBLE NOT NULL DEFAULT 0,
  PRIMARY KEY (`answer_code`, `bodySurveyQuestions_question_code`, `bodySurveyQuestions_headersSurvey_survey_code`, `bodySurveyQuestions_headersSurvey_bussinessUnit_bu_bis_code`),
  CONSTRAINT `fk_bodySurveyAnswers_bodySurveyQuestions1`
    FOREIGN KEY (`bodySurveyQuestions_question_code` , `bodySurveyQuestions_headersSurvey_survey_code` , `bodySurveyQuestions_headersSurvey_bussinessUnit_bu_bis_code`)
    REFERENCES `objectboard_db`.`bodySurveyQuestions` (`question_code` , `headersSurvey_survey_code` , `headersSurvey_bussinessUnit_bu_bis_code`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_bodySurveyAnswers_bodySurveyQuestions1_idx` ON `objectboard_db`.`bodySurveyAnswers` (`bodySurveyQuestions_question_code` ASC, `bodySurveyQuestions_headersSurvey_survey_code` ASC, `bodySurveyQuestions_headersSurvey_bussinessUnit_bu_bis_code` ASC);


-- -----------------------------------------------------
-- Table `objectboard_db`.`certifications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `objectboard_db`.`certifications` ;

CREATE TABLE IF NOT EXISTS `objectboard_db`.`certifications` (
  `certification_code` BIGINT(4) NOT NULL AUTO_INCREMENT,
  `bussinessUnit_bu_bis_code` BIGINT(4) NOT NULL,
  `name` VARCHAR(90) NULL,
  PRIMARY KEY (`certification_code`, `bussinessUnit_bu_bis_code`),
  CONSTRAINT `fk_process_bussinessUnit1`
    FOREIGN KEY (`bussinessUnit_bu_bis_code`)
    REFERENCES `objectboard_db`.`bussinessUnit` (`bu_bis_code`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_process_bussinessUnit1_idx` ON `objectboard_db`.`certifications` (`bussinessUnit_bu_bis_code` ASC);


-- -----------------------------------------------------
-- Table `objectboard_db`.`assignments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `objectboard_db`.`assignments` ;

CREATE TABLE IF NOT EXISTS `objectboard_db`.`assignments` (
  `masterUser_mu_email` VARCHAR(40) NOT NULL,
  `masterUser_bussinessUnit_bu_bis_code` BIGINT(4) NOT NULL,
  `headersSurvey_survey_code` BIGINT(8) NOT NULL,
  `date_start` VARCHAR(19) NULL,
  `frecuency` INT(3) NULL,
  `timeByFrecuency` INT(3) NULL,
  `notes` BIGINT(4) NULL DEFAULT 0,
  `legends` BIGINT(4) NULL DEFAULT 0,
  `exceptions` BIGINT(4) NULL DEFAULT 0,
  `terms` BIGINT(4) NULL DEFAULT 0,
  PRIMARY KEY (`masterUser_mu_email`, `masterUser_bussinessUnit_bu_bis_code`, `headersSurvey_survey_code`),
  CONSTRAINT `fk_assignments_masterUser1`
    FOREIGN KEY (`masterUser_mu_email` , `masterUser_bussinessUnit_bu_bis_code`)
    REFERENCES `objectboard_db`.`masterUser` (`mu_email` , `bussinessUnit_bu_bis_code`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_assignments_headersSurvey1`
    FOREIGN KEY (`headersSurvey_survey_code`)
    REFERENCES `objectboard_db`.`headersSurvey` (`survey_code`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_assignments_masterUser1_idx` ON `objectboard_db`.`assignments` (`masterUser_mu_email` ASC, `masterUser_bussinessUnit_bu_bis_code` ASC);

CREATE INDEX `fk_assignments_headersSurvey1_idx` ON `objectboard_db`.`assignments` (`headersSurvey_survey_code` ASC);


-- -----------------------------------------------------
-- Table `objectboard_db`.`process`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `objectboard_db`.`process` ;

CREATE TABLE IF NOT EXISTS `objectboard_db`.`process` (
  `process_code` BIGINT(4) NOT NULL AUTO_INCREMENT,
  `certifications_certification_code` BIGINT(4) NOT NULL,
  `certifications_bussinessUnit_bu_bis_code` BIGINT(4) NOT NULL,
  `headersSurvey_survey_code` BIGINT(8) NOT NULL,
  `status` VARCHAR(1) NULL DEFAULT 'F',
  PRIMARY KEY (`process_code`, `certifications_certification_code`, `certifications_bussinessUnit_bu_bis_code`, `headersSurvey_survey_code`),
  CONSTRAINT `fk_process_certifications1`
    FOREIGN KEY (`certifications_certification_code` , `certifications_bussinessUnit_bu_bis_code`)
    REFERENCES `objectboard_db`.`certifications` (`certification_code` , `bussinessUnit_bu_bis_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_process_headersSurvey1`
    FOREIGN KEY (`headersSurvey_survey_code`)
    REFERENCES `objectboard_db`.`headersSurvey` (`survey_code`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_process_certifications1_idx` ON `objectboard_db`.`process` (`certifications_certification_code` ASC, `certifications_bussinessUnit_bu_bis_code` ASC);

CREATE INDEX `fk_process_headersSurvey1_idx` ON `objectboard_db`.`process` (`headersSurvey_survey_code` ASC);


-- -----------------------------------------------------
-- Table `objectboard_db`.`comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `objectboard_db`.`comments` ;

CREATE TABLE IF NOT EXISTS `objectboard_db`.`comments` (
  `comment_code` BIGINT(4) NOT NULL AUTO_INCREMENT,
  `bussinessUnit_bu_bis_code` BIGINT(4) NOT NULL,
  `comment_type` VARCHAR(1) NULL,
  `comment_description` VARCHAR(180) NULL,
  `comment_reference` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`comment_code`, `bussinessUnit_bu_bis_code`),
  CONSTRAINT `fk_process_bussinessUnit10`
    FOREIGN KEY (`bussinessUnit_bu_bis_code`)
    REFERENCES `objectboard_db`.`bussinessUnit` (`bu_bis_code`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_process_bussinessUnit1_idx` ON `objectboard_db`.`comments` (`bussinessUnit_bu_bis_code` ASC);


-- -----------------------------------------------------
-- Table `objectboard_db`.`headerConductSurvey`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `objectboard_db`.`headerConductSurvey` ;

CREATE TABLE IF NOT EXISTS `objectboard_db`.`headerConductSurvey` (
  `conduct_id` BIGINT(8) NOT NULL AUTO_INCREMENT,
  `headersSurvey_survey_code` BIGINT(8) NOT NULL,
  `headersSurvey_bussinessUnit_bu_bis_code` BIGINT(4) NOT NULL,
  `masterUser_mu_email` VARCHAR(40) NOT NULL COMMENT 'user assignement',
  `conduct_date` VARCHAR(19) NOT NULL,
  `masterUser_bussinessUnit_bu_bis_code` BIGINT(4) NOT NULL,
  `auditable` VARCHAR(1) NOT NULL DEFAULT 'F',
  `to_audited` VARCHAR(1) NOT NULL DEFAULT 'T',
  `user_auditor` VARCHAR(40) NULL,
  `user_conduct` VARCHAR(40) NULL,
  `notes_code` BIGINT(4) NULL,
  `legends_code` BIGINT(4) NULL,
  `exceptions_code` BIGINT(4) NULL,
  `terms_code` BIGINT(4) NULL,
  `conformities` INT(3) NOT NULL DEFAULT 0,
  `non_conformities` INT(3) NOT NULL DEFAULT 0,
  `total_points_raised` DOUBLE NOT NULL DEFAULT 0,
  `total_points_achieved` DOUBLE NOT NULL DEFAULT 0,
  PRIMARY KEY (`conduct_id`, `headersSurvey_survey_code`, `headersSurvey_bussinessUnit_bu_bis_code`, `masterUser_mu_email`, `conduct_date`),
  CONSTRAINT `fk_headerConductSurvey_headersSurvey1`
    FOREIGN KEY (`headersSurvey_survey_code` , `headersSurvey_bussinessUnit_bu_bis_code`)
    REFERENCES `objectboard_db`.`headersSurvey` (`survey_code` , `bussinessUnit_bu_bis_code`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_headerConductSurvey_masterUser1`
    FOREIGN KEY (`masterUser_mu_email` , `masterUser_bussinessUnit_bu_bis_code`)
    REFERENCES `objectboard_db`.`masterUser` (`mu_email` , `bussinessUnit_bu_bis_code`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_noteCode`
    FOREIGN KEY (`notes_code`)
    REFERENCES `objectboard_db`.`comments` (`comment_code`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_legendCode`
    FOREIGN KEY (`legends_code`)
    REFERENCES `objectboard_db`.`comments` (`comment_code`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_exceptionCode`
    FOREIGN KEY (`exceptions_code`)
    REFERENCES `objectboard_db`.`comments` (`comment_code`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_termCode`
    FOREIGN KEY (`terms_code`)
    REFERENCES `objectboard_db`.`comments` (`comment_code`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_headerConductSurvey_headersSurvey1_idx` ON `objectboard_db`.`headerConductSurvey` (`headersSurvey_survey_code` ASC, `headersSurvey_bussinessUnit_bu_bis_code` ASC);

CREATE INDEX `fk_headerConductSurvey_masterUser1_idx` ON `objectboard_db`.`headerConductSurvey` (`masterUser_mu_email` ASC, `masterUser_bussinessUnit_bu_bis_code` ASC);

CREATE INDEX `fk_noteCode_idx` ON `objectboard_db`.`headerConductSurvey` (`notes_code` ASC);

CREATE INDEX `fk_legendCode_idx` ON `objectboard_db`.`headerConductSurvey` (`legends_code` ASC);

CREATE INDEX `fk_exceptionCode_idx` ON `objectboard_db`.`headerConductSurvey` (`exceptions_code` ASC);

CREATE INDEX `fk_termCode_idx` ON `objectboard_db`.`headerConductSurvey` (`terms_code` ASC);


-- -----------------------------------------------------
-- Table `objectboard_db`.`bodyConductSurvey`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `objectboard_db`.`bodyConductSurvey` ;

CREATE TABLE IF NOT EXISTS `objectboard_db`.`bodyConductSurvey` (
  `headerConductSurvey_conduct_id` BIGINT(8) NOT NULL,
  `bsa_bodySurveyQuestions_question_code` BIGINT(4) NOT NULL,
  `bsa_bodySurveyQuestions_headersSurvey_survey_code` BIGINT(8) NOT NULL,
  `bsa_bodySurveyQuestions_headersSurvey_bussinessUnit_bu_bis_code` BIGINT(4) NOT NULL,
  `bcs_answer_only_text` VARCHAR(45) NULL,
  `bcs_answer_only_number` DOUBLE NOT NULL DEFAULT 0,
  `bcs_answer_only_date` VARCHAR(10) NULL,
  `bcs_answer_only_time` VARCHAR(8) NULL,
  `bcs_comment` VARCHAR(145) NULL,
  `bcs_answer` VARCHAR(45) NULL,
  `bcs_type_request` INT(2) NOT NULL,
  `bcs_name_annex_file` VARCHAR(65) NULL,
  `bcs_annex_type` VARCHAR(1) NULL,
  `bcs_answer_solution` VARCHAR(45) NULL,
  `status_audit` VARCHAR(1) NOT NULL DEFAULT 'F',
  `result_audit` VARCHAR(1) NOT NULL DEFAULT 'F',
  `points` DOUBLE NOT NULL DEFAULT 0,
  `audit_note` VARCHAR(145) NULL,
  `status_rank` VARCHAR(1) NOT NULL DEFAULT 'F',
  `rank_min` DOUBLE NOT NULL DEFAULT 0,
  `rank_max` DOUBLE NOT NULL DEFAULT 0,
  `bcs_annex_file` LONGBLOB NULL,
  PRIMARY KEY (`headerConductSurvey_conduct_id`, `bsa_bodySurveyQuestions_question_code`, `bsa_bodySurveyQuestions_headersSurvey_survey_code`, `bsa_bodySurveyQuestions_headersSurvey_bussinessUnit_bu_bis_code`),
  CONSTRAINT `fk_bodyConductSurvey_bodySurveyAnswers1`
    FOREIGN KEY (`bsa_bodySurveyQuestions_question_code` , `bsa_bodySurveyQuestions_headersSurvey_survey_code` , `bsa_bodySurveyQuestions_headersSurvey_bussinessUnit_bu_bis_code`)
    REFERENCES `objectboard_db`.`bodySurveyAnswers` (`bodySurveyQuestions_question_code` , `bodySurveyQuestions_headersSurvey_survey_code` , `bodySurveyQuestions_headersSurvey_bussinessUnit_bu_bis_code`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_conduct_id`
    FOREIGN KEY (`headerConductSurvey_conduct_id`)
    REFERENCES `objectboard_db`.`headerConductSurvey` (`conduct_id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_bodyConductSurvey_bodySurveyAnswers1_idx` ON `objectboard_db`.`bodyConductSurvey` (`bsa_bodySurveyQuestions_question_code` ASC, `bsa_bodySurveyQuestions_headersSurvey_survey_code` ASC, `bsa_bodySurveyQuestions_headersSurvey_bussinessUnit_bu_bis_code` ASC);


-- -----------------------------------------------------
-- Table `objectboard_db`.`contactus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `objectboard_db`.`contactus` ;

CREATE TABLE IF NOT EXISTS `objectboard_db`.`contactus` (
  `ct_id` INT(8) NOT NULL AUTO_INCREMENT,
  `ct_nombre` VARCHAR(45) NOT NULL,
  `ct_phone` VARCHAR(10) NOT NULL,
  `ct_date` VARCHAR(19) NOT NULL,
  `ct_message` VARCHAR(160) NULL,
  `ct_email` VARCHAR(45) NULL,
  PRIMARY KEY (`ct_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `objectboard_db`.`contacts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `objectboard_db`.`contacts` ;

CREATE TABLE IF NOT EXISTS `objectboard_db`.`contacts` (
  `masterUser_bussinessUnit_bu_bis_code` BIGINT(4) NOT NULL,
  `masterUser_mu_email` VARCHAR(40) NOT NULL,
  `cto_email_direction` VARCHAR(45) NOT NULL,
  `cto_name` VARCHAR(45) NULL,
  `cto_business_name` VARCHAR(45) NULL,
  `cto_address_1` VARCHAR(45) NULL,
  `cto_address_2` VARCHAR(45) NULL,
  `cto_phone_cell` VARCHAR(12) NOT NULL,
  `cto_landline` VARCHAR(12) NULL,
  `cto_email_message` VARCHAR(1) NULL DEFAULT 'F',
  `cto_sms_message` VARCHAR(1) NULL DEFAULT 'F',
  `cto_front_yard` VARCHAR(1) NULL DEFAULT 'F',
  `cto_back_yard` VARCHAR(1) NULL DEFAULT 'F',
  `cto_type` VARCHAR(1) NULL DEFAULT 'E',
  PRIMARY KEY (`masterUser_bussinessUnit_bu_bis_code`, `masterUser_mu_email`, `cto_email_direction`),
  CONSTRAINT `fk_contacts_masterUser1`
    FOREIGN KEY (`masterUser_mu_email` , `masterUser_bussinessUnit_bu_bis_code`)
    REFERENCES `objectboard_db`.`masterUser` (`mu_email` , `bussinessUnit_bu_bis_code`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_contacts_masterUser1_idx` ON `objectboard_db`.`contacts` (`masterUser_mu_email` ASC, `masterUser_bussinessUnit_bu_bis_code` ASC);


-- -----------------------------------------------------
-- Table `objectboard_db`.`contacts_list`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `objectboard_db`.`contacts_list` ;

CREATE TABLE IF NOT EXISTS `objectboard_db`.`contacts_list` (
  `list_id` INT(11) NOT NULL AUTO_INCREMENT,
  `contacts_masterUser_bussinessUnit_bu_bis_code` BIGINT(4) NOT NULL,
  `contacts_masterUser_mu_email` VARCHAR(40) NOT NULL,
  `contacts_cto_email_direction` VARCHAR(45) NOT NULL,
  `list_project` BIGINT(2) NOT NULL DEFAULT 0,
  PRIMARY KEY (`list_id`),
  CONSTRAINT `fk_contacts_list_contacts1`
    FOREIGN KEY (`contacts_masterUser_bussinessUnit_bu_bis_code` , `contacts_masterUser_mu_email` , `contacts_cto_email_direction`)
    REFERENCES `objectboard_db`.`contacts` (`masterUser_bussinessUnit_bu_bis_code` , `masterUser_mu_email` , `cto_email_direction`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_contacts_list_contacts1_idx` ON `objectboard_db`.`contacts_list` (`contacts_masterUser_bussinessUnit_bu_bis_code` ASC, `contacts_masterUser_mu_email` ASC, `contacts_cto_email_direction` ASC);


-- -----------------------------------------------------
-- Table `objectboard_db`.`message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `objectboard_db`.`message` ;

CREATE TABLE IF NOT EXISTS `objectboard_db`.`message` (
  `msg_id` INT(11) NOT NULL AUTO_INCREMENT,
  `masterUser_mu_email` VARCHAR(40) NOT NULL,
  `masterUser_bussinessUnit_bu_bis_code` BIGINT(4) NOT NULL,
  `msg_project` BIGINT(2) NOT NULL,
  `msg_send_type` VARCHAR(1) NOT NULL,
  `msg_object_type` VARCHAR(1) NOT NULL,
  `msg_to` VARCHAR(90) NULL,
  `msg_cc` VARCHAR(90) NULL,
  `msg_cco` VARCHAR(90) NULL,
  `msg_to_list` INT(11) NULL DEFAULT 0,
  `msg_cc_list` INT(11) NULL DEFAULT 0,
  `msg_cco_list` INT(11) NULL DEFAULT 0,
  `msg_subject` VARCHAR(180) NULL,
  `msg_message` VARCHAR(360) NULL,
  `msg_survey_code` BIGINT(8) NULL,
  PRIMARY KEY (`msg_id`),
  CONSTRAINT `fk_message_masterUser1`
    FOREIGN KEY (`masterUser_mu_email` , `masterUser_bussinessUnit_bu_bis_code`)
    REFERENCES `objectboard_db`.`masterUser` (`mu_email` , `bussinessUnit_bu_bis_code`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_message_masterUser1_idx` ON `objectboard_db`.`message` (`masterUser_mu_email` ASC, `masterUser_bussinessUnit_bu_bis_code` ASC);

USE `objectboard_db` ;

-- -----------------------------------------------------
-- Placeholder table for view `objectboard_db`.`StateCountry`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `objectboard_db`.`StateCountry` (`id_state` INT, `state_name` INT, `id_country` INT, `country_name` INT);

-- -----------------------------------------------------
-- Placeholder table for view `objectboard_db`.`CityStateCountry`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `objectboard_db`.`CityStateCountry` (`id_city` INT, `id_state` INT, `id_country` INT, `city_name` INT, `state_name` INT, `country_name` INT);

-- -----------------------------------------------------
-- Placeholder table for view `objectboard_db`.`Profiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `objectboard_db`.`Profiles` (`mu_email` INT, `bussinessUnit_bu_bis_code` INT, `mu_password` INT, `mu_password_old` INT, `mu_name` INT, `mu_section_time` INT, `mu_question` INT, `mu_start_date` INT, `mu_answer` INT, `mu_status` INT, `mu_date` INT, `mu_effective_days` INT, `mu_confirm_code` INT, `mu_email_confirm` INT, `mu_date_reset_pwd` INT, `mu_gender` INT, `mu_photo` INT, `mu_data_user` INT, `mu_data_password` INT, `mu_expires` INT, `mu_date_expires` INT, `city_ci_city_code` INT, `city_states_st_state_code` INT, `city_states_country_co_country_code` INT, `mu_photo_name` INT, `contry_name` INT, `state_name` INT, `city_name` INT, `bu_name` INT);

-- -----------------------------------------------------
-- Placeholder table for view `objectboard_db`.`BussinessUnitCoStCi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `objectboard_db`.`BussinessUnitCoStCi` (`bu_bis_code` INT, `bu_federal_number` INT, `bu_provincial_number` INT, `bu_email` INT, `bu_status` INT, `bu_super_code` INT, `bu_phone` INT, `bu_zipcode` INT, `bu_name` INT, `bu_address` INT, `bu_webpage` INT, `bu_admin_code` INT, `bu_user1_code` INT, `bu_user2_code` INT, `city_ci_city_code` INT, `city_states_st_state_code` INT, `city_states_country_co_country_code` INT, `bussinessType_bt_code_type` INT, `bu_logo_name` INT, `bu_logo_image` INT, `city_name` INT, `state_name` INT, `country_name` INT, `type_name` INT);

-- -----------------------------------------------------
-- Placeholder table for view `objectboard_db`.`DischargeView`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `objectboard_db`.`DischargeView` (`di_license_num` INT, `di_start_date` INT, `di_end_date` INT, `di_number_user` INT, `di_permanent` INT, `di_sales_code` INT, `di_license_code` INT, `bussinessUnit_bu_bis_code` INT, `project_pr_id_project` INT, `bu_name` INT, `pr_name` INT);

-- -----------------------------------------------------
-- Placeholder table for view `objectboard_db`.`UserRoleView`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `objectboard_db`.`UserRoleView` (`masterUser_mu_email` INT, `masterUser_bussinessUnit_bu_bis_code` INT, `project_pr_id_project` INT, `um_role` INT, `um_status` INT, `user_name` INT, `unit_name` INT, `proj_name` INT);

-- -----------------------------------------------------
-- Placeholder table for view `objectboard_db`.`SurveyTotalView`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `objectboard_db`.`SurveyTotalView` (`survey_code` INT, `bussinessUnit_code` INT, `survey_name` INT, `hs_references` INT, `total_questions` INT, `surveyStatus` INT, `execution_status` INT, `version` INT, `date_creation` INT, `typified_ctypified_code1` INT, `typified_ctypified_code2` INT, `typified_ctypified_code3` INT, `organization_level1` INT, `organization_level2` INT, `organization_level3` INT, `organization_level4` INT, `date_last_modification` INT, `audited` INT, `question_code` INT, `type_request` INT, `main_request` INT, `Annex_type` INT, `body_annex_doc` INT, `body_annex_photo` INT, `comment` INT, `answer_number` INT, `solution_number` INT, `auditable_question_solution` INT, `auditable_inquestion_answer_solution` INT, `answer_code` INT, `answer` INT, `answer_solution` INT, `auditable_answer_solution` INT, `answer_only_text` INT, `answer_only_number` INT, `answer_only_date` INT, `answer_only_time` INT);

-- -----------------------------------------------------
-- View `objectboard_db`.`StateCountry`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `objectboard_db`.`StateCountry`;
DROP VIEW IF EXISTS `objectboard_db`.`StateCountry` ;
USE `objectboard_db`;
CREATE  OR REPLACE VIEW `StateCountry` AS
    SELECT 
        st_state_code AS id_state,
        st_name AS state_name,
        co_country_code AS id_country,
        co_name AS country_name
    FROM
        states,
        country
    WHERE
        country_co_country_code = co_country_code;

-- -----------------------------------------------------
-- View `objectboard_db`.`CityStateCountry`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `objectboard_db`.`CityStateCountry`;
DROP VIEW IF EXISTS `objectboard_db`.`CityStateCountry` ;
USE `objectboard_db`;
CREATE 
     OR REPLACE ALGORITHM = UNDEFINED 
    DEFINER = `boarduser`@`%` 
    SQL SECURITY DEFINER
VIEW `objectboard_db`.`CityStateCountry` AS
  select ct.ci_city_code AS id_city,
       ct.states_st_state_code AS id_state,
       ct.states_country_co_country_code AS id_country,
       ct.ci_name AS city_name,
       st.st_name AS state_name,
       co.co_name AS country_name
       FROM objectboard_db.city ct, objectboard_db.states st,  objectboard_db.country co
       WHERE (ct.states_st_state_code=st.st_state_code AND ct.states_country_co_country_code=co.co_country_code);

-- -----------------------------------------------------
-- View `objectboard_db`.`Profiles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `objectboard_db`.`Profiles`;
DROP VIEW IF EXISTS `objectboard_db`.`Profiles` ;
USE `objectboard_db`;
CREATE  OR REPLACE VIEW `Profiles` AS
    SELECT 
        M.*,
        P.co_name AS contry_name,
        S.st_name AS state_name,
        C.ci_name AS city_name,
        B.bu_name AS bu_name
    FROM
        objectboard_db.masterUser M,
        objectboard_db.country P,
        objectboard_db.states S,
        objectboard_db.city C,
        objectboard_db.bussinessUnit B
    WHERE
        (M.city_states_country_co_country_code = P.co_country_code
            AND M.city_states_st_state_code = S.st_state_code
            AND M.city_ci_city_code = C.ci_city_code
            AND M.bussinessUnit_bu_bis_code = B.bu_bis_code);

-- -----------------------------------------------------
-- View `objectboard_db`.`BussinessUnitCoStCi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `objectboard_db`.`BussinessUnitCoStCi`;
DROP VIEW IF EXISTS `objectboard_db`.`BussinessUnitCoStCi` ;
USE `objectboard_db`;
CREATE 
     OR REPLACE ALGORITHM = UNDEFINED 
    DEFINER = `boarduser`@`%` 
    SQL SECURITY DEFINER
VIEW `objectboard_db`.`BussinessUnitCoStCi` AS
  select bb.*,
       ct.ci_name AS city_name,
       st.st_name AS state_name,
       co.co_name AS country_name,
       bt.bt_description AS type_name
       FROM objectboard_db.bussinessUnit bb,
			objectboard_db.states st,
            objectboard_db.country co,
            objectboard_db.city ct,
            objectboard_db.bussinessType bt
       WHERE (bb.city_ci_city_code=ct.ci_city_code AND 
              bb.city_states_st_state_code=st.st_state_code AND
              bb.city_states_country_co_country_code=co.co_country_code AND
              bb.bussinessType_bt_code_type=bt.bt_code_type);

-- -----------------------------------------------------
-- View `objectboard_db`.`DischargeView`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `objectboard_db`.`DischargeView`;
DROP VIEW IF EXISTS `objectboard_db`.`DischargeView` ;
USE `objectboard_db`;
CREATE  OR REPLACE VIEW `DischargeView` AS
    SELECT 
        D.*, B.bu_name, P.pr_name
    FROM
        discharge D,
        bussinessUnit B,
        project P
    WHERE
        (B.bu_bis_code = D.bussinessUnit_bu_bis_code
            AND P.pr_id_project = D.project_pr_id_project);

-- -----------------------------------------------------
-- View `objectboard_db`.`UserRoleView`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `objectboard_db`.`UserRoleView`;
DROP VIEW IF EXISTS `objectboard_db`.`UserRoleView` ;
USE `objectboard_db`;
CREATE  OR REPLACE VIEW `UserRoleView` AS
    SELECT 
        UR.*,
        MU.mu_name AS user_name,
        BU.bu_name AS unit_name,
        PR.pr_name AS proj_name
    FROM
        userRole UR,
        masterUser MU,
        bussinessUnit BU,
        project PR
    WHERE
        (UR.masterUser_mu_email = MU.mu_email
            AND UR.masterUser_bussinessUnit_bu_bis_code = MU.bussinessUnit_bu_bis_code)
            AND (UR.masterUser_bussinessUnit_bu_bis_code = BU.bu_bis_code)
            AND (UR.project_pr_id_project = PR.pr_id_project);

-- -----------------------------------------------------
-- View `objectboard_db`.`SurveyTotalView`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `objectboard_db`.`SurveyTotalView`;
DROP VIEW IF EXISTS `objectboard_db`.`SurveyTotalView` ;
USE `objectboard_db`;
CREATE  OR REPLACE VIEW `SurveyTotalView` AS
SELECT HS.survey_code,
HS.bussinessUnit_bu_bis_code	AS bussinessUnit_code,
HS.hs_name AS survey_name,
HS.hs_references,
HS.total_questions,
HS.surveyStatus,
HS.execution_status,
HS.version,
HS.date_creation,
HS.typified_ctypified_code1,
HS.typified_ctypified_code2,
HS.typified_ctypified_code3,
HS.organization_level1,
HS.organization_level2,
HS.organization_level3,
HS.organization_level4,
HS.date_last_modification,
HS.audited,
BQ.question_code,
BQ.type_request,
BQ.main_request,
BQ.Annex_type,
BQ.body_annex_doc,
BQ.body_annex_photo,
BQ.comment,
BQ.answer_number,
BQ.solution_number,
BQ.auditable_solution AS auditable_question_solution,
BQ.auditable_answer_solution AS auditable_inquestion_answer_solution,
BA.answer_code,
BA.answer,
BA.answer_solution,
BA.auditable_solution AS auditable_answer_solution,
BA.answer_only_text,
BA.answer_only_number,
BA.answer_only_date,
BA.answer_only_time
FROM objectboard_db.headersSurvey HS, 
     objectboard_db.bodySurveyQuestions BQ,
     objectboard_db.bodySurveyAnswers BA
WHERE ((BQ.headersSurvey_survey_code = HS.survey_code AND 
       BQ.headersSurvey_bussinessUnit_bu_bis_code = HS.bussinessUnit_bu_bis_code) AND
       (BA.bodySurveyQuestions_question_code = BQ.question_code AND
        BA.bodySurveyQuestions_headersSurvey_survey_code = BQ.headersSurvey_survey_code AND
        BA.bodySurveyQuestions_headersSurvey_bussinessUnit_bu_bis_code = BQ.headersSurvey_bussinessUnit_bu_bis_code));

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `objectboard_db`.`country`
-- -----------------------------------------------------
START TRANSACTION;
USE `objectboard_db`;
INSERT INTO `objectboard_db`.`country` (`co_country_code`, `co_name`) VALUES (DEFAULT, 'Canada');
INSERT INTO `objectboard_db`.`country` (`co_country_code`, `co_name`) VALUES (DEFAULT, 'Usa');
INSERT INTO `objectboard_db`.`country` (`co_country_code`, `co_name`) VALUES (DEFAULT, 'Venezuela');
INSERT INTO `objectboard_db`.`country` (`co_country_code`, `co_name`) VALUES (DEFAULT, 'Republica Dominicana');
INSERT INTO `objectboard_db`.`country` (`co_country_code`, `co_name`) VALUES (DEFAULT, 'Colombia');
INSERT INTO `objectboard_db`.`country` (`co_country_code`, `co_name`) VALUES (DEFAULT, 'Japon');
INSERT INTO `objectboard_db`.`country` (`co_country_code`, `co_name`) VALUES (DEFAULT, 'Francia');
INSERT INTO `objectboard_db`.`country` (`co_country_code`, `co_name`) VALUES (DEFAULT, 'Alemania');
INSERT INTO `objectboard_db`.`country` (`co_country_code`, `co_name`) VALUES (DEFAULT, 'Australia');
INSERT INTO `objectboard_db`.`country` (`co_country_code`, `co_name`) VALUES (DEFAULT, 'Noruega');
INSERT INTO `objectboard_db`.`country` (`co_country_code`, `co_name`) VALUES (DEFAULT, 'Irlanda');
INSERT INTO `objectboard_db`.`country` (`co_country_code`, `co_name`) VALUES (DEFAULT, 'Argentina');
INSERT INTO `objectboard_db`.`country` (`co_country_code`, `co_name`) VALUES (DEFAULT, 'Uruguay');
INSERT INTO `objectboard_db`.`country` (`co_country_code`, `co_name`) VALUES (DEFAULT, 'El Salvador');
INSERT INTO `objectboard_db`.`country` (`co_country_code`, `co_name`) VALUES (DEFAULT, 'Nicaragua');
INSERT INTO `objectboard_db`.`country` (`co_country_code`, `co_name`) VALUES (DEFAULT, 'Panama');
INSERT INTO `objectboard_db`.`country` (`co_country_code`, `co_name`) VALUES (DEFAULT, 'Peru');
INSERT INTO `objectboard_db`.`country` (`co_country_code`, `co_name`) VALUES (DEFAULT, 'Ecuador');
INSERT INTO `objectboard_db`.`country` (`co_country_code`, `co_name`) VALUES (DEFAULT, 'Guatemala');
INSERT INTO `objectboard_db`.`country` (`co_country_code`, `co_name`) VALUES (DEFAULT, 'Bolivia');
INSERT INTO `objectboard_db`.`country` (`co_country_code`, `co_name`) VALUES (DEFAULT, 'Brasil');
INSERT INTO `objectboard_db`.`country` (`co_country_code`, `co_name`) VALUES (DEFAULT, 'España');
INSERT INTO `objectboard_db`.`country` (`co_country_code`, `co_name`) VALUES (DEFAULT, 'Mexico');
INSERT INTO `objectboard_db`.`country` (`co_country_code`, `co_name`) VALUES (DEFAULT, 'Gran Bretaña');
INSERT INTO `objectboard_db`.`country` (`co_country_code`, `co_name`) VALUES (DEFAULT, 'Portugal');
INSERT INTO `objectboard_db`.`country` (`co_country_code`, `co_name`) VALUES (DEFAULT, 'China');
INSERT INTO `objectboard_db`.`country` (`co_country_code`, `co_name`) VALUES (DEFAULT, 'Corea del Sur');
INSERT INTO `objectboard_db`.`country` (`co_country_code`, `co_name`) VALUES (DEFAULT, 'Corea del Norte');
INSERT INTO `objectboard_db`.`country` (`co_country_code`, `co_name`) VALUES (DEFAULT, 'Singapur');
INSERT INTO `objectboard_db`.`country` (`co_country_code`, `co_name`) VALUES (DEFAULT, 'Croasia');
INSERT INTO `objectboard_db`.`country` (`co_country_code`, `co_name`) VALUES (DEFAULT, 'Mongolia');

COMMIT;


-- -----------------------------------------------------
-- Data for table `objectboard_db`.`states`
-- -----------------------------------------------------
START TRANSACTION;
USE `objectboard_db`;
INSERT INTO `objectboard_db`.`states` (`st_state_code`, `country_co_country_code`, `st_name`) VALUES (DEFAULT, 1, 'Quebec');
INSERT INTO `objectboard_db`.`states` (`st_state_code`, `country_co_country_code`, `st_name`) VALUES (DEFAULT, 2, 'Tennessee');

COMMIT;


-- -----------------------------------------------------
-- Data for table `objectboard_db`.`city`
-- -----------------------------------------------------
START TRANSACTION;
USE `objectboard_db`;
INSERT INTO `objectboard_db`.`city` (`ci_city_code`, `states_st_state_code`, `states_country_co_country_code`, `ci_name`) VALUES (DEFAULT, 1, 1, 'Saint Hyacinthe');
INSERT INTO `objectboard_db`.`city` (`ci_city_code`, `states_st_state_code`, `states_country_co_country_code`, `ci_name`) VALUES (DEFAULT, 2, 2, 'Nashville');

COMMIT;


-- -----------------------------------------------------
-- Data for table `objectboard_db`.`bussinessType`
-- -----------------------------------------------------
START TRANSACTION;
USE `objectboard_db`;
INSERT INTO `objectboard_db`.`bussinessType` (`bt_code_type`, `bt_description`, `bt_note`) VALUES (DEFAULT, 'Desarrollo', 'nota relacionada');
INSERT INTO `objectboard_db`.`bussinessType` (`bt_code_type`, `bt_description`, `bt_note`) VALUES (DEFAULT, 'Primera industria', 'Prueba para clientes regulares');

COMMIT;


-- -----------------------------------------------------
-- Data for table `objectboard_db`.`bussinessUnit`
-- -----------------------------------------------------
START TRANSACTION;
USE `objectboard_db`;
INSERT INTO `objectboard_db`.`bussinessUnit` (`bu_bis_code`, `bu_federal_number`, `bu_provincial_number`, `bu_email`, `bu_status`, `bu_super_code`, `bu_phone`, `bu_zipcode`, `bu_name`, `bu_address`, `bu_webpage`, `bu_admin_code`, `bu_user1_code`, `bu_user2_code`, `city_ci_city_code`, `city_states_st_state_code`, `city_states_country_co_country_code`, `bussinessType_bt_code_type`, `bu_logo_name`, `bu_logo_image`) VALUES (DEFAULT, '0123456789', '0123456789012345', 'pepe@gmail.com', 'T', 'ASDFJKLNMOPQ', '305-258-3689', 'jkl369', 'Servicios PVSoft LLc', 'Case de Carajo', 'pepe.com', 'AWQRCFDSHBNF', 'OPLKIUJHYTGF', 'UYTREDSWQAZX', 1, 1, 1, 1, DEFAULT, NULL);
INSERT INTO `objectboard_db`.`bussinessUnit` (`bu_bis_code`, `bu_federal_number`, `bu_provincial_number`, `bu_email`, `bu_status`, `bu_super_code`, `bu_phone`, `bu_zipcode`, `bu_name`, `bu_address`, `bu_webpage`, `bu_admin_code`, `bu_user1_code`, `bu_user2_code`, `city_ci_city_code`, `city_states_st_state_code`, `city_states_country_co_country_code`, `bussinessType_bt_code_type`, `bu_logo_name`, `bu_logo_image`) VALUES (DEFAULT, '9876543210', '5432109876543210', 'pavelaz1@gmail.com', 'T', 'DFRSC56780AS', '302-258-9874', '123456', 'Test Company LLc', 'En el patio', 'luis.com', '0987654321QW', 'GHJKLMNBVCXZ', '1Q2W3E4R5T6Y', 1, 1, 1, 1, DEFAULT, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `objectboard_db`.`project`
-- -----------------------------------------------------
START TRANSACTION;
USE `objectboard_db`;
INSERT INTO `objectboard_db`.`project` (`pr_id_project`, `pr_name`, `pr_note`) VALUES (DEFAULT, 'Dashboard', 'nota relacionada');
INSERT INTO `objectboard_db`.`project` (`pr_id_project`, `pr_name`, `pr_note`) VALUES (DEFAULT, 'Autobuses', 'relacionada al bus');

COMMIT;


-- -----------------------------------------------------
-- Data for table `objectboard_db`.`discharge`
-- -----------------------------------------------------
START TRANSACTION;
USE `objectboard_db`;
INSERT INTO `objectboard_db`.`discharge` (`di_license_num`, `di_start_date`, `di_end_date`, `di_number_user`, `di_permanent`, `di_sales_code`, `di_license_code`, `bussinessUnit_bu_bis_code`, `project_pr_id_project`) VALUES (DEFAULT, '2020/10/03', '2020/10/09', 5, 'F', 1, 'ASDFGHJKL9876543', 1, 1);

COMMIT;

