-- MySQL Script generated by MySQL Workbench
-- mar 05 may 2020 10:08:31 CDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema objectboard_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema objectboard_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `objectboard_db` DEFAULT CHARACTER SET utf8 ;
USE `objectboard_db` ;

-- -----------------------------------------------------
-- Table `objectboard_db`.`Log_country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `objectboard_db`.`Log_country` ;

CREATE TABLE IF NOT EXISTS `objectboard_db`.`Log_country` (
  `co_country_code` BIGINT(3) NULL,
  `co_name` VARCHAR(40) NULL,
  `co_name_old` VARCHAR(40) NULL,
  `action` VARCHAR(8) NULL,
  `who` VARCHAR(12) NULL,
  `when` VARCHAR(20) NULL)
ENGINE = InnoDB
COMMENT = 'Country list';


-- -----------------------------------------------------
-- Table `objectboard_db`.`Log_states`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `objectboard_db`.`Log_states` ;

CREATE TABLE IF NOT EXISTS `objectboard_db`.`Log_states` (
  `st_state_code` BIGINT(2) NOT NULL AUTO_INCREMENT,
  `country_co_country_code` BIGINT(3) NOT NULL,
  `st_name` VARCHAR(45) NULL,
  `st_name_old` VARCHAR(45) NULL,
  `action` VARCHAR(8) NULL,
  `who` VARCHAR(12) NULL,
  `when` VARCHAR(20) NULL,
  PRIMARY KEY (`st_state_code`, `country_co_country_code`))
ENGINE = InnoDB
COMMENT = 'State List';


-- -----------------------------------------------------
-- Table `objectboard_db`.`Log_city`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `objectboard_db`.`Log_city` ;

CREATE TABLE IF NOT EXISTS `objectboard_db`.`Log_city` (
  `ci_city_code` BIGINT(3) NULL,
  `states_st_state_code` BIGINT(2) NULL,
  `states_country_co_country_code` BIGINT(3) NULL,
  `ci_name` VARCHAR(45) NULL,
  `ci_name_old` VARCHAR(45) NULL,
  `action` VARCHAR(8) NULL,
  `who` VARCHAR(12) NULL,
  `when` VARCHAR(20) NULL)
ENGINE = InnoDB
COMMENT = 'City List';


-- -----------------------------------------------------
-- Table `objectboard_db`.`bussinessType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `objectboard_db`.`bussinessType` ;

CREATE TABLE IF NOT EXISTS `objectboard_db`.`bussinessType` (
  `bt_code_type` BIGINT(2) NOT NULL AUTO_INCREMENT,
  `bt_description` VARCHAR(45) NOT NULL,
  `bt_note` VARCHAR(85) NULL,
  PRIMARY KEY (`bt_code_type`))
ENGINE = InnoDB
COMMENT = 'type of business unit';


-- -----------------------------------------------------
-- Table `objectboard_db`.`bussinessUnit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `objectboard_db`.`bussinessUnit` ;

CREATE TABLE IF NOT EXISTS `objectboard_db`.`bussinessUnit` (
  `bu_bis_code` BIGINT(4) NOT NULL AUTO_INCREMENT COMMENT 'Clavede la tabla - numero de la empresa',
  `bu_federal_number` VARCHAR(10) NULL,
  `bu_provincial_number` VARCHAR(16) NULL,
  `bu_email` VARCHAR(60) NULL,
  `bu_status` VARCHAR(1) NOT NULL DEFAULT 'T' COMMENT '1 ACTIVE 0 INACTIVE',
  `bu_super_code` VARCHAR(12) NULL COMMENT 'COMPANY CODE TO REGISTER ADMINISTRATORS',
  `bu_phone` VARCHAR(13) NULL,
  `bu_zipcode` VARCHAR(6) NULL,
  `bu_name` VARCHAR(35) NULL,
  `bu_address` VARCHAR(45) NULL,
  `bu_webpage` VARCHAR(50) NULL,
  `country_co_country_code` BIGINT(3) NOT NULL,
  `states_st_state_code` BIGINT(2) NOT NULL,
  `states_country_co_country_code` BIGINT(3) NOT NULL,
  `city_ci_city_code` BIGINT(3) NOT NULL,
  `city_states_st_state_code` BIGINT(2) NOT NULL,
  `city_states_country_co_country_code` BIGINT(3) NOT NULL,
  `bussinessType_bt_code_type` BIGINT(2) NOT NULL,
  PRIMARY KEY (`bu_bis_code`),
  CONSTRAINT `fk_bussinessUnit_country1`
    FOREIGN KEY (`country_co_country_code`)
    REFERENCES `objectboard_db`.`Log_country` (`co_country_code`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bussinessUnit_states1`
    FOREIGN KEY (`states_st_state_code` , `states_country_co_country_code`)
    REFERENCES `objectboard_db`.`Log_states` (`st_state_code` , `country_co_country_code`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bussinessUnit_city1`
    FOREIGN KEY (`city_ci_city_code` , `city_states_st_state_code` , `city_states_country_co_country_code`)
    REFERENCES `objectboard_db`.`Log_city` (`ci_city_code` , `states_st_state_code` , `states_country_co_country_code`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bussinessUnit_bussinessType1`
    FOREIGN KEY (`bussinessType_bt_code_type`)
    REFERENCES `objectboard_db`.`bussinessType` (`bt_code_type`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_bussinessUnit_country1_idx` ON `objectboard_db`.`bussinessUnit` (`country_co_country_code` ASC);

CREATE INDEX `fk_bussinessUnit_states1_idx` ON `objectboard_db`.`bussinessUnit` (`states_st_state_code` ASC, `states_country_co_country_code` ASC);

CREATE INDEX `fk_bussinessUnit_city1_idx` ON `objectboard_db`.`bussinessUnit` (`city_ci_city_code` ASC, `city_states_st_state_code` ASC, `city_states_country_co_country_code` ASC);

CREATE INDEX `fk_bussinessUnit_bussinessType1_idx` ON `objectboard_db`.`bussinessUnit` (`bussinessType_bt_code_type` ASC);


-- -----------------------------------------------------
-- Table `objectboard_db`.`project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `objectboard_db`.`project` ;

CREATE TABLE IF NOT EXISTS `objectboard_db`.`project` (
  `pr_id_project` BIGINT(2) NOT NULL AUTO_INCREMENT,
  `pr_name` VARCHAR(45) NOT NULL,
  `pr_note` VARCHAR(145) NULL,
  PRIMARY KEY (`pr_id_project`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `objectboard_db`.`discharge`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `objectboard_db`.`discharge` ;

CREATE TABLE IF NOT EXISTS `objectboard_db`.`discharge` (
  `di_license_num` BIGINT(8) NOT NULL AUTO_INCREMENT,
  `di_start_date` VARCHAR(19) NOT NULL,
  `di_end_date` VARCHAR(19) NOT NULL,
  `di_number_user` INT(3) NULL,
  `di_permanent` VARCHAR(1) NULL DEFAULT 'F',
  `di_sales_code` INT(2) NULL DEFAULT 0,
  `di_license_code` VARCHAR(16) NOT NULL,
  `bussinessUnit_bu_bis_code` BIGINT(4) NOT NULL,
  `project_pr_id_project` BIGINT(2) NOT NULL,
  PRIMARY KEY (`di_license_num`),
  CONSTRAINT `fk_discharge_bussinessUnit1`
    FOREIGN KEY (`bussinessUnit_bu_bis_code`)
    REFERENCES `objectboard_db`.`bussinessUnit` (`bu_bis_code`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_discharge_project1`
    FOREIGN KEY (`project_pr_id_project`)
    REFERENCES `objectboard_db`.`project` (`pr_id_project`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_discharge_bussinessUnit1_idx` ON `objectboard_db`.`discharge` (`bussinessUnit_bu_bis_code` ASC);

CREATE INDEX `fk_discharge_project1_idx` ON `objectboard_db`.`discharge` (`project_pr_id_project` ASC);


-- -----------------------------------------------------
-- Table `objectboard_db`.`masterUser`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `objectboard_db`.`masterUser` ;

CREATE TABLE IF NOT EXISTS `objectboard_db`.`masterUser` (
  `mu_email` VARCHAR(40) NOT NULL,
  `bussinessUnit_bu_bis_code` BIGINT(4) NOT NULL,
  `mu_password` VARCHAR(20) NOT NULL,
  `mu_password_old` VARCHAR(20) NULL,
  `mu_name` VARCHAR(45) NULL,
  `mu_section_time` INT(11) NULL DEFAULT 1200 COMMENT 'TIEMPO QUE PERMANECE ABIERTA LA SECCION EN DESUSO',
  `mu_question` VARCHAR(60) NULL,
  `mu_start_date` VARCHAR(19) NOT NULL COMMENT 'start date ',
  `mu_answer` VARCHAR(35) NULL,
  `mu_status` VARCHAR(1) NOT NULL DEFAULT 'F' COMMENT '0 INACTIVE 1 ACTIVE',
  `mu_date` VARCHAR(19) NOT NULL COMMENT 'REGISTER DATE',
  `mu_effective_days` INT(4) NOT NULL DEFAULT 90 COMMENT 'renovation password days',
  `mu_confirm_code` VARCHAR(45) NULL,
  `mu_email_confirm` VARCHAR(1) NULL DEFAULT 'F' COMMENT '0 UNCONFIRM 1 CONFIRM',
  `mu_date_reset_pwd` VARCHAR(19) NULL,
  `mu_gender` VARCHAR(1) NULL DEFAULT 'M',
  `mu_photo` BLOB NULL,
  `mu_data_user` VARCHAR(12) NULL COMMENT 'long para accesar la base de datos',
  `mu_data_password` VARCHAR(12) NULL,
  `mu_expires` VARCHAR(1) NULL DEFAULT 'F',
  `mu_time_expires` INT(4) NULL DEFAULT 90,
  `country_co_country_code` BIGINT(3) NOT NULL,
  `states_st_state_code` BIGINT(2) NOT NULL,
  `states_country_co_country_code` BIGINT(3) NOT NULL,
  `city_ci_city_code` BIGINT(3) NOT NULL,
  `city_states_st_state_code` BIGINT(2) NOT NULL COMMENT 'EL ACCESO AL SISTEMA CADUCA O NO',
  `city_states_country_co_country_code` BIGINT(3) NOT NULL,
  PRIMARY KEY (`mu_email`, `bussinessUnit_bu_bis_code`),
  CONSTRAINT `fk_masterUser_bussinessUnit1`
    FOREIGN KEY (`bussinessUnit_bu_bis_code`)
    REFERENCES `objectboard_db`.`bussinessUnit` (`bu_bis_code`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_masterUser_country1`
    FOREIGN KEY (`country_co_country_code`)
    REFERENCES `objectboard_db`.`Log_country` (`co_country_code`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_masterUser_states1`
    FOREIGN KEY (`states_st_state_code` , `states_country_co_country_code`)
    REFERENCES `objectboard_db`.`Log_states` (`st_state_code` , `country_co_country_code`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_masterUser_city1`
    FOREIGN KEY (`city_ci_city_code` , `city_states_st_state_code` , `city_states_country_co_country_code`)
    REFERENCES `objectboard_db`.`Log_city` (`ci_city_code` , `states_st_state_code` , `states_country_co_country_code`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_masterUser_bussinessUnit1_idx` ON `objectboard_db`.`masterUser` (`bussinessUnit_bu_bis_code` ASC);

CREATE INDEX `fk_masterUser_country1_idx` ON `objectboard_db`.`masterUser` (`country_co_country_code` ASC);

CREATE INDEX `fk_masterUser_states1_idx` ON `objectboard_db`.`masterUser` (`states_st_state_code` ASC, `states_country_co_country_code` ASC);

CREATE INDEX `fk_masterUser_city1_idx` ON `objectboard_db`.`masterUser` (`city_ci_city_code` ASC, `city_states_st_state_code` ASC, `city_states_country_co_country_code` ASC);


-- -----------------------------------------------------
-- Table `objectboard_db`.`userRole`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `objectboard_db`.`userRole` ;

CREATE TABLE IF NOT EXISTS `objectboard_db`.`userRole` (
  `masterUser_mu_email` VARCHAR(40) NOT NULL,
  `masterUser_bussinessUnit_bu_bis_code` BIGINT(4) NOT NULL,
  `project_pr_id_project` BIGINT(2) NOT NULL,
  `um_role` INT(2) NOT NULL DEFAULT 0 COMMENT 'INTRANET USERS',
  `um_status` VARCHAR(1) NULL DEFAULT 'T' COMMENT 'active or not',
  PRIMARY KEY (`masterUser_mu_email`, `masterUser_bussinessUnit_bu_bis_code`, `project_pr_id_project`),
  CONSTRAINT `fk_userRole_masterUser1`
    FOREIGN KEY (`masterUser_mu_email` , `masterUser_bussinessUnit_bu_bis_code`)
    REFERENCES `objectboard_db`.`masterUser` (`mu_email` , `bussinessUnit_bu_bis_code`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_userRole_project1`
    FOREIGN KEY (`project_pr_id_project`)
    REFERENCES `objectboard_db`.`project` (`pr_id_project`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'modules to which each user has access by business unit';

CREATE INDEX `fk_userRole_project1_idx` ON `objectboard_db`.`userRole` (`project_pr_id_project` ASC);

USE `objectboard_db` ;

-- -----------------------------------------------------
-- Placeholder table for view `objectboard_db`.`StateCountry`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `objectboard_db`.`StateCountry` (`id_state` INT, `state_name` INT, `id_country` INT, `country_name` INT);

-- -----------------------------------------------------
-- Placeholder table for view `objectboard_db`.`CityStateCountry`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `objectboard_db`.`CityStateCountry` (`id_city` INT, `id_state` INT, `id_country` INT, `city_name` INT, `state_name` INT, `country_name` INT);

-- -----------------------------------------------------
-- View `objectboard_db`.`StateCountry`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `objectboard_db`.`StateCountry` ;
DROP TABLE IF EXISTS `objectboard_db`.`StateCountry`;
USE `objectboard_db`;
CREATE  OR REPLACE VIEW `StateCountry` AS
    SELECT 
        st_state_code AS id_state,
        st_name AS state_name,
        co_country_code AS id_country,
        co_name AS country_name
    FROM
        states,
        country
    WHERE
        country_co_country_code = co_country_code;

-- -----------------------------------------------------
-- View `objectboard_db`.`CityStateCountry`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `objectboard_db`.`CityStateCountry` ;
DROP TABLE IF EXISTS `objectboard_db`.`CityStateCountry`;
USE `objectboard_db`;
CREATE 
     OR REPLACE ALGORITHM = UNDEFINED 
    DEFINER = `boarduser`@`%` 
    SQL SECURITY DEFINER
VIEW `objectboard_db`.`CityStateCountry` AS
  select ct.ci_city_code AS id_city,
       ct.states_st_state_code AS id_state,
       ct.states_country_co_country_code AS id_country,
       ct.ci_name AS city_name,
       st.st_name AS state_name,
       co.co_name AS country_name
       FROM objectboard_db.city ct, objectboard_db.states st,  objectboard_db.country co
       WHERE (ct.states_st_state_code=st.st_state_code AND ct.states_country_co_country_code=co.co_country_code);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `objectboard_db`.`Log_country`
-- -----------------------------------------------------
START TRANSACTION;
USE `objectboard_db`;
INSERT INTO `objectboard_db`.`Log_country` (`co_country_code`, `co_name`, `co_name_old`, `action`, `who`, `when`) VALUES (NULL, 'Canada', NULL, NULL, NULL, NULL);
INSERT INTO `objectboard_db`.`Log_country` (`co_country_code`, `co_name`, `co_name_old`, `action`, `who`, `when`) VALUES (NULL, 'Usa', NULL, NULL, NULL, NULL);
INSERT INTO `objectboard_db`.`Log_country` (`co_country_code`, `co_name`, `co_name_old`, `action`, `who`, `when`) VALUES (NULL, 'Venezuela', NULL, NULL, NULL, NULL);
INSERT INTO `objectboard_db`.`Log_country` (`co_country_code`, `co_name`, `co_name_old`, `action`, `who`, `when`) VALUES (NULL, 'Republica Dominicana', NULL, NULL, NULL, NULL);
INSERT INTO `objectboard_db`.`Log_country` (`co_country_code`, `co_name`, `co_name_old`, `action`, `who`, `when`) VALUES (NULL, 'Colombia', NULL, NULL, NULL, NULL);
INSERT INTO `objectboard_db`.`Log_country` (`co_country_code`, `co_name`, `co_name_old`, `action`, `who`, `when`) VALUES (NULL, 'Japon', NULL, NULL, NULL, NULL);
INSERT INTO `objectboard_db`.`Log_country` (`co_country_code`, `co_name`, `co_name_old`, `action`, `who`, `when`) VALUES (NULL, 'Francia', NULL, NULL, NULL, NULL);
INSERT INTO `objectboard_db`.`Log_country` (`co_country_code`, `co_name`, `co_name_old`, `action`, `who`, `when`) VALUES (NULL, 'Alemania', NULL, NULL, NULL, NULL);
INSERT INTO `objectboard_db`.`Log_country` (`co_country_code`, `co_name`, `co_name_old`, `action`, `who`, `when`) VALUES (NULL, 'Australia', NULL, NULL, NULL, NULL);
INSERT INTO `objectboard_db`.`Log_country` (`co_country_code`, `co_name`, `co_name_old`, `action`, `who`, `when`) VALUES (NULL, 'Noruega', NULL, NULL, NULL, NULL);
INSERT INTO `objectboard_db`.`Log_country` (`co_country_code`, `co_name`, `co_name_old`, `action`, `who`, `when`) VALUES (NULL, 'Irlanda', NULL, NULL, NULL, NULL);
INSERT INTO `objectboard_db`.`Log_country` (`co_country_code`, `co_name`, `co_name_old`, `action`, `who`, `when`) VALUES (NULL, 'Argentina', NULL, NULL, NULL, NULL);
INSERT INTO `objectboard_db`.`Log_country` (`co_country_code`, `co_name`, `co_name_old`, `action`, `who`, `when`) VALUES (NULL, 'Uruguay', NULL, NULL, NULL, NULL);
INSERT INTO `objectboard_db`.`Log_country` (`co_country_code`, `co_name`, `co_name_old`, `action`, `who`, `when`) VALUES (NULL, 'El Salvador', NULL, NULL, NULL, NULL);
INSERT INTO `objectboard_db`.`Log_country` (`co_country_code`, `co_name`, `co_name_old`, `action`, `who`, `when`) VALUES (NULL, 'Nicaragua', NULL, NULL, NULL, NULL);
INSERT INTO `objectboard_db`.`Log_country` (`co_country_code`, `co_name`, `co_name_old`, `action`, `who`, `when`) VALUES (NULL, 'Panama', NULL, NULL, NULL, NULL);
INSERT INTO `objectboard_db`.`Log_country` (`co_country_code`, `co_name`, `co_name_old`, `action`, `who`, `when`) VALUES (NULL, 'Peru', NULL, NULL, NULL, NULL);
INSERT INTO `objectboard_db`.`Log_country` (`co_country_code`, `co_name`, `co_name_old`, `action`, `who`, `when`) VALUES (NULL, 'Ecuador', NULL, NULL, NULL, NULL);
INSERT INTO `objectboard_db`.`Log_country` (`co_country_code`, `co_name`, `co_name_old`, `action`, `who`, `when`) VALUES (NULL, 'Guatemala', NULL, NULL, NULL, NULL);
INSERT INTO `objectboard_db`.`Log_country` (`co_country_code`, `co_name`, `co_name_old`, `action`, `who`, `when`) VALUES (NULL, 'Bolivia', NULL, NULL, NULL, NULL);
INSERT INTO `objectboard_db`.`Log_country` (`co_country_code`, `co_name`, `co_name_old`, `action`, `who`, `when`) VALUES (NULL, 'Brasil', NULL, NULL, NULL, NULL);
INSERT INTO `objectboard_db`.`Log_country` (`co_country_code`, `co_name`, `co_name_old`, `action`, `who`, `when`) VALUES (NULL, 'España', NULL, NULL, NULL, NULL);
INSERT INTO `objectboard_db`.`Log_country` (`co_country_code`, `co_name`, `co_name_old`, `action`, `who`, `when`) VALUES (NULL, 'Mexico', NULL, NULL, NULL, NULL);
INSERT INTO `objectboard_db`.`Log_country` (`co_country_code`, `co_name`, `co_name_old`, `action`, `who`, `when`) VALUES (NULL, 'Gran Bretaña', NULL, NULL, NULL, NULL);
INSERT INTO `objectboard_db`.`Log_country` (`co_country_code`, `co_name`, `co_name_old`, `action`, `who`, `when`) VALUES (NULL, 'Portugal', NULL, NULL, NULL, NULL);
INSERT INTO `objectboard_db`.`Log_country` (`co_country_code`, `co_name`, `co_name_old`, `action`, `who`, `when`) VALUES (NULL, 'China', NULL, NULL, NULL, NULL);
INSERT INTO `objectboard_db`.`Log_country` (`co_country_code`, `co_name`, `co_name_old`, `action`, `who`, `when`) VALUES (NULL, 'Corea del Sur', NULL, NULL, NULL, NULL);
INSERT INTO `objectboard_db`.`Log_country` (`co_country_code`, `co_name`, `co_name_old`, `action`, `who`, `when`) VALUES (NULL, 'Corea del Norte', NULL, NULL, NULL, NULL);
INSERT INTO `objectboard_db`.`Log_country` (`co_country_code`, `co_name`, `co_name_old`, `action`, `who`, `when`) VALUES (NULL, 'Singapur', NULL, NULL, NULL, NULL);
INSERT INTO `objectboard_db`.`Log_country` (`co_country_code`, `co_name`, `co_name_old`, `action`, `who`, `when`) VALUES (NULL, 'Croasia', NULL, NULL, NULL, NULL);
INSERT INTO `objectboard_db`.`Log_country` (`co_country_code`, `co_name`, `co_name_old`, `action`, `who`, `when`) VALUES (NULL, 'Mongolia', NULL, NULL, NULL, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `objectboard_db`.`Log_states`
-- -----------------------------------------------------
START TRANSACTION;
USE `objectboard_db`;
INSERT INTO `objectboard_db`.`Log_states` (`st_state_code`, `country_co_country_code`, `st_name`, `st_name_old`, `action`, `who`, `when`) VALUES (DEFAULT, 1, 'Quebec', NULL, NULL, NULL, NULL);
INSERT INTO `objectboard_db`.`Log_states` (`st_state_code`, `country_co_country_code`, `st_name`, `st_name_old`, `action`, `who`, `when`) VALUES (DEFAULT, 2, 'Tennessee', NULL, NULL, NULL, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `objectboard_db`.`Log_city`
-- -----------------------------------------------------
START TRANSACTION;
USE `objectboard_db`;
INSERT INTO `objectboard_db`.`Log_city` (`ci_city_code`, `states_st_state_code`, `states_country_co_country_code`, `ci_name`, `ci_name_old`, `action`, `who`, `when`) VALUES (NULL, 1, 1, 'Saint Hyacinthe', NULL, NULL, NULL, NULL);
INSERT INTO `objectboard_db`.`Log_city` (`ci_city_code`, `states_st_state_code`, `states_country_co_country_code`, `ci_name`, `ci_name_old`, `action`, `who`, `when`) VALUES (NULL, 2, 2, 'Nashville', NULL, NULL, NULL, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `objectboard_db`.`bussinessType`
-- -----------------------------------------------------
START TRANSACTION;
USE `objectboard_db`;
INSERT INTO `objectboard_db`.`bussinessType` (`bt_code_type`, `bt_description`, `bt_note`) VALUES (DEFAULT, 'Desarrollo', 'nota relacionada');
INSERT INTO `objectboard_db`.`bussinessType` (`bt_code_type`, `bt_description`, `bt_note`) VALUES (DEFAULT, 'Primera industria', 'Prueba para clientes regulares');

COMMIT;


-- -----------------------------------------------------
-- Data for table `objectboard_db`.`bussinessUnit`
-- -----------------------------------------------------
START TRANSACTION;
USE `objectboard_db`;
INSERT INTO `objectboard_db`.`bussinessUnit` (`bu_bis_code`, `bu_federal_number`, `bu_provincial_number`, `bu_email`, `bu_status`, `bu_super_code`, `bu_phone`, `bu_zipcode`, `bu_name`, `bu_address`, `bu_webpage`, `country_co_country_code`, `states_st_state_code`, `states_country_co_country_code`, `city_ci_city_code`, `city_states_st_state_code`, `city_states_country_co_country_code`, `bussinessType_bt_code_type`) VALUES (DEFAULT, '0123456789', '0123456789012345', 'pepe@gmail.com', 'T', 'ASDFJKLNMOPQ', '305-258-3689', 'jkl369', 'Servicios PVSoft LLc', 'Case de Carajo', 'pepe.com', 1, 1, 1, 1, 1, 1, 1);
INSERT INTO `objectboard_db`.`bussinessUnit` (`bu_bis_code`, `bu_federal_number`, `bu_provincial_number`, `bu_email`, `bu_status`, `bu_super_code`, `bu_phone`, `bu_zipcode`, `bu_name`, `bu_address`, `bu_webpage`, `country_co_country_code`, `states_st_state_code`, `states_country_co_country_code`, `city_ci_city_code`, `city_states_st_state_code`, `city_states_country_co_country_code`, `bussinessType_bt_code_type`) VALUES (DEFAULT, '9876543210', '5432109876543210', 'pavelaz1@gmail.com', 'T', 'DFRSC5678', '302-258-9874', '123456', 'Test Company LLc', 'En el patio', 'luis.com', 2, 1, 1, 1, 1, 1, 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `objectboard_db`.`project`
-- -----------------------------------------------------
START TRANSACTION;
USE `objectboard_db`;
INSERT INTO `objectboard_db`.`project` (`pr_id_project`, `pr_name`, `pr_note`) VALUES (DEFAULT, 'Dashboard', 'nota relacionada');
INSERT INTO `objectboard_db`.`project` (`pr_id_project`, `pr_name`, `pr_note`) VALUES (DEFAULT, 'Autobuses', 'relacionada al bus');

COMMIT;


-- -----------------------------------------------------
-- Data for table `objectboard_db`.`discharge`
-- -----------------------------------------------------
START TRANSACTION;
USE `objectboard_db`;
INSERT INTO `objectboard_db`.`discharge` (`di_license_num`, `di_start_date`, `di_end_date`, `di_number_user`, `di_permanent`, `di_sales_code`, `di_license_code`, `bussinessUnit_bu_bis_code`, `project_pr_id_project`) VALUES (DEFAULT, '2020-10-03', '2020-10-09', 5, '0', 1, 'ASDFGHJKL9876543', 1, 1);

COMMIT;

